[package]
name = "core-service"
version = "0.1.0"
edition = "2021"
description = "Simplified Rust service used for integration tests"
authors = ["X.400 Modernization Team"]
license = "MIT"

[dependencies]

[dev-dependencies]
