[package]
name = "core-service"
version = "0.1.0"
edition = "2021"
description = "Rust background service providing IPC for the X.400 modernization project"
authors = ["X.400 Modernization Team"]
license = "MIT"

[dependencies]
anyhow = "1.0"
axum = "0.7"
chrono = { version = "0.4", features = ["serde"] }

config = { version = "0.13", default-features = false, features = ["json", "toml"] }

keyring = "2.3"
once_cell = "1.19"
openssl = { version = "0.10", features = ["vendored", "chrono"] }
libloading = "0.8"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.4"
sha2 = "0.10"

sqlx = { version = "0.8", default-features = false, features = [
  "runtime-tokio-rustls",
  "sqlite",
  "macros",
  "chrono"
] }

thiserror = "1.0"

tokio = { version = "1.35", features = ["macros", "rt-multi-thread", "signal", "time"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1.7", features = ["serde", "v4"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tempfile = "3.10"
tower = "0.4"

[[bench]]
name = "submit_loop"
harness = false
