[package]
name = "core-service"
version = "0.1.0"
edition = "2021"
description = "Simplified Rust service used for integration tests"
authors = ["X.400 Modernization Team"]
license = "MIT"

[dependencies]

chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
chardetng = "0.1"
encoding_rs = "0.8"
sha2 = "0.10"
walkdir = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
unicode-normalization = "0.1"

[dev-dependencies]
tempfile = "3"
