version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://localhost:16686']
      interval: 30s
      timeout: 5s
      retries: 3
  prometheus:
    image: prom/prometheus:v2.50.0
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - '3000:3000'
    volumes:
      - ./observability/grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - jaeger
