name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build workspace artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('packages/core-service/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build monorepo (excluding docs)
        run: pnpm build

  lint:
    name: Lint & format checks
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run JS/TS lint
        run: pnpm lint
      - name: Run Rust lint
        run: pnpm --filter @x400/core-service run lint
      - name: Check formatting (Rust)
        run: pnpm --filter @x400/core-service exec cargo fmt --all -- --check

  test:
    name: Unit & integration tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run workspace tests
        run: pnpm test:all

  e2e:
    name: Playwright end-to-end tests
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers (linux)
        if: runner.os == 'Linux'
        run: pnpm exec playwright install --with-deps
      - name: Install Playwright browsers (windows)
        if: runner.os != 'Linux'
        run: pnpm exec playwright install
      - name: Run e2e tests
        run: pnpm e2e
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report
          if-no-files-found: ignore

  audit:
    name: Dependency security audit
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Audit Node dependencies
        run: pnpm audit --prod
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Audit Rust dependencies
        run: pnpm --filter @x400/core-service run audit

  docs:
    name: Build documentation site
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install mkdocs tooling
        run: pip install mkdocs mkdocs-material
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build docs
        run: pnpm --filter @x400/docs run docs:build
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: packages/docs/site
          if-no-files-found: error
